feature_cols = [ 'all_res_total_fl_area_H_total',
                        'Pre 1919_pct',
                        'Standard size detached_pct',
                        'postcode_area',
                        'HDD_winter',  
                        'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                        'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                        'socio_class_perc_L1, L2 and L3: Higher managerial, administrative and professional occupations',
                        'household_comp_perc_One-person household',
                        'Domestic outbuilding_pct',
                        '3-4 storey and smaller flats_pct',
                        ] 